### ISSUE TITLE
Update for retina screens?

### ISSUE THREAD

**Issue by quantumgolem** [kainjow/FoolSaver#1]
Not sure if this is just me or something, but it seems like the logo and artwork has non-retina resolution. It would be really cool to update it for the retina screen!

**Comment by kainjow** [comment]
The images would need to be recreated from scratch. I'm not a designer, but if someone wants to and sends them my way I'd be happy to incorporate them.

**Comment by quantumgolem** [comment]
@kainjow I'm trying attempting it right now, but I'm just trying to replace 0.png. How would I do this? I'm trying to put a 144 dpi image in, but it still looks bigger. It doesn't seem to be "retina"

**Comment by kainjow** [comment]
You would need an image twice the width and height at same 72 dpi and give it the same name, but add "@2x" to it. For example "0@2x.png".

**Comment by quantumgolem** [comment]
For some reason that didn't work for me (it didn't seem to "see" the @2x.png file), but I was able to get it done by changing the resolution and PPI of image. Thanks.
